### ISSUE TITLE
Add static files to build

### ISSUE THREAD

**Issue by whatrocks** [benjreinhart/syte#2]
I'd like to add static files (e.g. robots.txt, favicon.ico) to the `/build` directory so that my deploy process can run `syte build`.

**Comment by benjreinhart** [comment]
Yessss, me too... (backwards incompatible) changes for this [here](https://github.com/benjreinhart/syte/commit/d2861cd9988e75081a37cf73b582642a55d141e9) and [here](https://github.com/benjreinhart/syte/commit/29ee7657efb23cd68f2c8bdf438832ce841a9e82).

0.0.1-beta.7 contains those commits.
